package br.uea.transirie.mypay.mycoffee.repository.sqlite

const val DATABASE_VERSION = 1
const val DATABASE_NAME = "dbApp"

const val TABLE_SERVICO = "servico"
const val TABLE_CLIENTE = "cliente"
const val TABLE_ATENDIMENTO = "atendimento"
const val TABLE_ESTABELECIMENTO = "estabelecimento"
const val TABLE_ITEM_ATENDIMENTO = "itemAtendimento"
const val TABLE_PAGAMENTO = "pagamento"
const val COLUMN_ID = "_id"
const val COLUMN_CLIENTE_ID = "clienteId"
const val COLUMN_DESCRICAO = "descricao"
const val COLUMN_PRECO = "preco"
const val COLUMN_DATA_RECEBIMENTO = "dataRecebimento"
const val COLUMN_DATA_PREVISAO_ENTREGA = "dataPrevisaoEntrega"
const val COLUMN_DATA_CONCLUSAO = "dataConclusao"
const val COLUMN_VALOR_TOTAL = "valorTotal"
const val COLUMN_NOME = "nome"
const val COLUMN_EMAIL = "email"
const val COLUMN_DATA_NASCIMENTO = "dataNascimento"
const val COLUMN_CPF = "cpf"
const val COLUMN_VALOR = "valor"
const val COLUMN_DATA_PAGAMENTO = "dataPagamento"
const val COLUMN_SENHA_OBFUSCATED = "senhaObfuscated"
const val COLUMN_NOME_FANTASIA = "nomeFantasia"
const val COLUMN_RAZAO_SOCIAL = "razaoSocial"
const val COLUMN_CNPJ = "cnpj"
const val COLUMN_TELEFONE = "telefone"
const val COLUMN_ENDERECO = "endereco"
const val COLUMN_ATENDIMENTO_ID = "atendimentoId"
const val COLUMN_TIPO_PAGAMENTO = "tipoPagamento"
const val COLUMN_SERVICO_ID = "servicoId"
const val COLUMN_ITEM_ATENDIMENTO_ID = "itemAtendimentoId"
